version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - simule_frete

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - simule_frete

    # db mysql
    db:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_USER: ${DB_USERNAME:-laravel_user}
            MYSQL_PASSWORD: ${DB_PASSWORD:-password}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
            - ./init-scripts:/docker-entrypoint-initdb.d
        ports:
            - "3388:3306"
        networks:
            - simule_frete


    # redis
    redis:
        image: redis:latest
        networks:
            - simule_frete
        # ...
    environment:
        MYSQL_DATABASE: ${DB_DATABASE:-laravel}
        MYSQL_USER: ${DB_USERNAME:-laravel_user}
        MYSQL_PASSWORD: ${DB_PASSWORD:-password}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password}

networks:
    simule_frete:
        driver: bridge